apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 
helmCharts:
- name: vector
  repo: https://helm.vector.dev
  version: v0.20.1
  namespace: vector
  releaseName: vector
  valuesFile: ./values.yaml
